"""init

Revision ID: 33c23a4b7d88
Revises: 
Create Date: 2025-07-16 20:29:55.081025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c23a4b7d88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=255), server_default='', nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), server_default='', nullable=False, comment='密码'),
    sa.Column('fullname', sa.String(length=255), server_default='', nullable=False, comment='姓名'),
    sa.Column('email', sa.String(length=255), server_default='', nullable=False, comment='邮箱'),
    sa.Column('mobile', sa.String(length=255), server_default='', nullable=False, comment='手机号'),
    sa.Column('gender', sa.SMALLINT(), server_default=sa.text('0'), nullable=False, comment='性别：1-男, 2-女'),
    sa.Column('status', sa.SMALLINT(), server_default=sa.text('1'), nullable=False, comment='状态：1-启用, 2-禁用'),
    sa.Column('user_type', sa.SMALLINT(), server_default=sa.text('0'), nullable=False, comment='用户类型：0-普通用户, 1-管理员'),
    sa.Column('last_login_time', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=255), server_default='', nullable=False, comment='最后登录IP'),
    sa.Column('is_delete', sa.SMALLINT(), server_default=sa.text('0'), nullable=False, comment='是否删除：0-否, 1-是'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_table('sys_user')
    # ### end Alembic commands ###
